// ============================================================
// DATA PERATURAN KETENAGANUKLIRAN
//   f   = nama file PDF (PERSIS sama dengan di folder dokumen/)
//   t   = judul tampilan
//   tag = array tema: 'industri', 'medik', 'instalasi'
// ============================================================

const SECTIONS = [

  // ══════════════════════════════════════════════════════════
  // UNDANG-UNDANG
  // ══════════════════════════════════════════════════════════
  { id:'s1', title:'Undang-Undang', cat:'uu', items:[
    { f:'UU 10 1997 Ketenaganukliran.pdf',
      t:'UU No. 10 Tahun 1997 – Ketenaganukliran', tag:['industri','medik','instalasi'] },
    { f:'UU 11 2020 Cipta Kerja.pdf',
      t:'UU No. 11 Tahun 2020 – Cipta Kerja', tag:['industri','medik','instalasi'] },
    { f:'UU 8 1978 Pengesahan Pencegahan Penyebaran Senjata Nuklir.pdf',
      t:'UU No. 8 Tahun 1978 – Pengesahan Perjanjian Pencegahan Penyebaran Senjata Nuklir (NPT)', tag:['instalasi'] },
    { f:'UU 9 1997 Pengesahan Traktat Kawasan Bebas Senjata Nuklir.pdf',
      t:'UU No. 9 Tahun 1997 – Pengesahan Traktat Kawasan Bebas Senjata Nuklir (SEANWFZ)', tag:['instalasi'] },
    { f:'UU 10 2012 Pengesahan Konvensi Penanggulangan Terorisme Nuklir.pdf',
      t:'UU No. 10 Tahun 2012 – Pengesahan Konvensi Penanggulangan Terorisme Nuklir', tag:['instalasi'] },
  ]},

  // ══════════════════════════════════════════════════════════
  // PERATURAN PEMERINTAH
  // ══════════════════════════════════════════════════════════
  { id:'s2', title:'Peraturan Pemerintah', cat:'pp', items:[
    { f:'PP 45 2023 Keselamatan Radiasi Pengion dan Keamanan ZR.pdf',
      t:'PP No. 45 Tahun 2023 – Keselamatan Radiasi Pengion dan Keamanan Zat Radioaktif', tag:['industri','medik'] },
    { f:'PP 42 2022 Jenis dan Tarif Atas Jenis PNBP.pdf',
      t:'PP No. 42 Tahun 2022 – Tarif dan Jenis PNBP yang Berlaku Pada BAPETEN', tag:['industri','medik','instalasi'] },
    { f:'PP 52 2022 Keselamatan dan Keamanan Pertambangan Bahan Galian Nuklir.pdf',
      t:'PP No. 52 Tahun 2022 – Keselamatan dan Keamanan Pertambangan Bahan Galian Nuklir', tag:['industri'] },
    { f:'PP 5 2021 Penyelenggaraan Perizinan Berusaha Berbasis Risiko.pdf',
      t:'PP No. 5 Tahun 2021 – Penyelenggaraan Perizinan Berusaha Berbasis Risiko', tag:['industri','medik','instalasi'] },
    { f:'PP 58 2015 Keselamatan dan Keamanan dalam Pengangkutan ZR.pdf',
      t:'PP No. 58 Tahun 2015 – Keselamatan dan Keamanan Dalam Pengangkutan Zat Radioaktif', tag:['industri','medik'] },
    { f:'PP 56 2014 Jenis dan Tarif Atas Jenis PNBP.pdf',
      t:'PP No. 56 Tahun 2014 – Jenis dan Tarif PNBP yang Berlaku Pada BAPETEN', tag:['industri','medik','instalasi'] },
    { f:'PP 2 2014 Perizinan IN dan BN.pdf',
      t:'PP No. 2 Tahun 2014 – Perizinan Instalasi Nuklir dan Pemanfaatan Bahan Nuklir', tag:['instalasi'] },
    { f:'PP 61 2012 Pengelolaan Limbah Radioaaktif.pdf',
      t:'PP No. 61 Tahun 2013 – Pengelolaan Limbah Radioaktif', tag:['industri','medik','instalasi'] },
    { f:'PP 54 2012 Keselamatan dan Keamanan Instasi Nuklir.pdf',
      t:'PP No. 54 Tahun 2012 – Keselamatan dan Keamanan Instalasi Nuklir', tag:['instalasi'] },
    { f:'PP 29 2009 Tata Cara Penetuan Jumlah Pembayaran, dan Penyetoran PNBP Terutang.pdf',
      t:'PP No. 29 Tahun 2009 – Tata Cara Penentuan Jumlah, Pembayaran, dan Penyetoran PNBP Terutang', tag:['industri','medik','instalasi'] },
    { f:'PP 46 2009 Batas Pertanggungjawaban Kerugian Nuklir.pdf',
      t:'PP No. 46 Tahun 2009 – Batas Pertanggungjawaban Kerugian Nuklir', tag:['instalasi'] },
    { f:'PP 27 2009 Jenis dan Tarif Atas Jenis PNBP.pdf',
      t:'PP No. 27 Tahun 2009 – Jenis dan Tarif PNBP yang Berlaku Pada BAPETEN', tag:['industri','medik','instalasi'] },
    { f:'PP 29 2008 Perizinan Pemanfaatan SRP dan BN.pdf',
      t:'PP No. 29 Tahun 2008 – Perizinan Pemanfaatan Sumber Radiasi Pengion dan Bahan Nuklir', tag:['industri','medik'] },
    { f:'PP 33 2007 Keselamatan Radiasi Pengion dan Keamanan ZR.pdf',
      t:'PP No. 33 Tahun 2007 – Keselamatan Radiasi Pengion dan Keamanan Sumber Radioaktif', tag:['industri','medik'] },
    { f:'PP 43 2006 Perizinan RN.pdf',
      t:'PP No. 43 Tahun 2006 – Perizinan Reaktor Nuklir', tag:['instalasi'] },
    { f:'PP 26 2002 Keselamatan Pengangkutan ZR.pdf',
      t:'PP No. 26 Tahun 2002 – Keselamatan Pengangkutan Zat Radioaktif', tag:['industri','medik'] },
    { f:'PP 27 2002 Pengelolaan Limbah Radioaktif.pdf',
      t:'PP No. 27 Tahun 2002 – Pengelolaan Limbah Radioaktif', tag:['industri','medik','instalasi'] },
    { f:'PP 28 Tahun 2025 Penyelenggaraan perizinan berusaha.pdf',
      t:'PP No. 28 Tahun 2025 – Penyelenggaraan Perizinan Berusaha', tag:['industri','medik','instalasi'] },
  ]},

  // ══════════════════════════════════════════════════════════
  // PERPRES & KEPPRES
  // ══════════════════════════════════════════════════════════
  { id:'s3', title:'Peraturan Presiden & Keputusan Presiden', cat:'perpres', items:[
    { f:'Perpres 60 2019 Kebijakan dan Strategis Nasional Nuklir.pdf',
      t:'PERPRES No. 60 Tahun 2019 – Kebijakan dan Strategi Nasional Keselamatan Nuklir Dan Radiasi', tag:['industri','medik','instalasi'] },
    { f:'Perpres 87 2014 Peraturan Pelaksanaan UU 12 2011 Pembantukan PUU.pdf',
      t:'PERPRES No. 87 Tahun 2014 – Peraturan Pelaksanaan UU No. 12 Tahun 2011', tag:['industri','medik','instalasi'] },
    { f:'Perpres 74 2012 Pertanggungjawaban Kerugian Nuklir.pdf',
      t:'PERPRES No. 74 Tahun 2012 – Pertanggungjawaban Kerugian Nuklir', tag:['instalasi'] },
    { f:'Perpres 84 2010 Pengesahan JC Spent fuel dan Radioactive waste.pdf',
      t:'PERPRES No. 84 Tahun 2010 – Pengesahan Joint Convention on The Safety of Spent Fuel Management', tag:['instalasi'] },
    { f:'Perpres 46 2009 Pengesahan Perubahan Konvensi Proteksi Fisik Bahan Nuklir.pdf',
      t:'PERPRES No. 46 Tahun 2009 – Pengesahan Perubahan Konvensi Proteksi Fisik Bahan Nuklir', tag:['instalasi'] },
    { f:'Kepres 106 2001 Pengesahan Convention on Nuclear Safety.pdf',
      t:'KEPPRES No. 106 Tahun 2001 – Pengesahan Convention on Nuclear Safety', tag:['instalasi'] },
    { f:'Kepres 82 1993 Pengesahan Convention on Assistance in the Case of Nuclear Accident.pdf',
      t:'KEPPRES No. 82 Tahun 1993 – Pengesahan Convention on Assistance in the Case of Nuclear Accident', tag:['instalasi'] },
    { f:'Kepres 81 1993 Pengesanan Convention on Early Notification Nuclear Accident.pdf',
      t:'KEPPRES No. 81 Tahun 1993 – Pengesahan Convention on Early Notification of A Nuclear Accident', tag:['instalasi'] },
    { f:'Kepres 80 1993 Pengesahan Amandemen Article VI IAEA.pdf',
      t:'KEPPRES No. 80 Tahun 1993 – Pengesahan Amandemen Article VI Statute of The IAEA', tag:['instalasi'] },
    { f:'Kepres 49 1986 Pengesahan Convention on Physical Protection.pdf',
      t:'KEPPRES No. 49 Tahun 1986 – Pengesahan Convention on The Physical Protection of Nuclear Material', tag:['instalasi'] },
  ]},

  // ══════════════════════════════════════════════════════════
  // PERATURAN BAPETEN (PERBA/PERKA)
  // ══════════════════════════════════════════════════════════
  { id:'s4a', title:'Peraturan BAPETEN 2024', cat:'perka', items:[
    { f:'Perba 05 2024 keamanan zat radioaktif.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2024 – Keamanan Zat Radioaktif', tag:['industri','medik'] },
    { f:'Perba 3 2024 Lartas Bapeten.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2024 – Pembatasan Impor dan Ekspor Barang Konsumen ZR dan PRP', tag:['industri'] },
    { f:'Perba 4 2024 Izin Pekerja Petugas pada Fasilitas Radiasi.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2024 – Izin Pekerja Petugas pada Fasilitas Radiasi', tag:['industri','medik'] },
  ]},

  { id:'s4b', title:'Peraturan BAPETEN 2022', cat:'perka', items:[
    { f:'Perba 01 2022 Penatalaksanaan Perizinan Berusaha.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2022 – Penatalaksanaan Perizinan Berusaha Berbasis Risiko Sektor Ketenaganukliran', tag:['industri','medik','instalasi'] },
    { f:'Perba 2 2022 Perubahan Perba 2 2028 Uji Kesesuaian Pesawat Radiologi Diagnostik.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2022 – Perubahan Perba No. 2 Tahun 2018 Tentang Uji Kesesuaian Pesawat Sinar-X Radiologi Diagnostik', tag:['medik'] },
    { f:'Perba 3 2022 Keselamatan Desain Teras Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2022 – Keselamatan Desain Teras Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 4 2022 Lab Uji Bungkusan ZR.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2022 – Laboratorium Uji Bungkusan Zat Radioaktif', tag:['industri'] },
    { f:'Perba 5 2022 Manajemen Penuaan RN.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2022 – Manajemen Penuaan Reaktor Nuklir', tag:['instalasi'] },
  ]},

  { id:'s4c', title:'Peraturan BAPETEN 2021', cat:'perka', items:[
    { f:'Perba 3 2021 Standar Kegiatan Usaha dan Standar Produk Perizinan Berusaha Sektor Kete....pdf',
      t:'Perba BAPETEN No. 3 Tahun 2021 – Standar Kegiatan Usaha dan Standar Produk Pada Penyelenggaraan Perizinan Berusaha Berbasis Risiko', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4d', title:'Peraturan BAPETEN 2020', cat:'perka', items:[
    { f:'Perba 1 2020 Aspek Proteksi Radiasi dalam Desain Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2020 – Aspek Proteksi Radiasi dalam Desain Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 3 2020 Keselamatan Radiasi Iradiator.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2020 – Keselamatan Radiasi Dalam Penggunaan Iradiator untuk Iradiasi', tag:['industri'] },
    { f:'Perba 4 2020 Keselamatan Radiasi Penggunaaan Pesawat RDI.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2020 – Keselamatan Radiasi Pada Penggunaan Pesawat Sinar-X Dalam Radiologi Diagnostik dan Intervensional', tag:['medik'] },
    { f:'Perba 5 2020 Justifikasi Pemanfaatan Sumber Radiasi Pengion.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2020 – Justifikasi Pemanfaatan Sumber Radiasi Pengion', tag:['industri','medik'] },
    { f:'Perba 6 2020 Keselamatan Radiasi Produksi Radioisotop dan Radiofarmaka.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2020 – Keselamatan Radiasi dalam Produksi Radioisotop untuk Radiofarmaka', tag:['medik'] },
    { f:'Perba 7 2020 Keselamatan Pengangkutan ZRA.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2020 – Ketentuan Keselamatan dan Tata Laksana Pengangkutan Zat Radioaktif', tag:['industri','medik'] },
    { f:'Perba 11 2020 Penyusunan LAK Rektor Daya.pdf',
      t:'Perba BAPETEN No. 11 Tahun 2020 – Penyusunan Laporan Analisis Keselamatan Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 12 2020 Klasifikasi SSK IN.pdf',
      t:'Perba BAPETEN No. 12 Tahun 2020 – Klasifikasi Struktur, Sistem, dan Komponen Instalasi Nuklir', tag:['instalasi'] },
  ]},

  { id:'s4e', title:'Peraturan BAPETEN 2019', cat:'perka', items:[
    { f:'Perba 2 2019 Keselamatan Komisioning Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2019 – Keselamatan Komisioning Reaktor Nondaya',
      lamp:[{l:'Lamp I', f:'Perba 2 2019 Keselamatan Komisioning Reaktor Non Daya (Lampiran I).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 4 2019 Evaluasi Tapak Instalasi Nuklir Aspek Dispersi.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2019 – Evaluasi Tapak Instalasi Nuklir untuk Aspek Dispersi Zat Radioaktif Di Udara dan Air', tag:['instalasi'] },
    { f:'Perba 5 2019 Penyusunan LAK INNR.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2019 – Penyusunan Laporan Analisis Keselamatan', tag:['instalasi'] },
    { f:'Perba 6 2019 Evaluasi Tapak IN Aspek Kejadian Eksternal.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2019 – Evaluasi Tapak Instalasi Nuklir untuk Aspek Kejadian Eksternal Akibat Ulah Manusia', tag:['instalasi'] },
    { f:'Perba 7 2019 Izin Bekerja Petugas IN dan BN.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2019 – Izin Bekerja Petugas Instalasi Nuklir dan Bahan Nuklir', tag:['instalasi'] },
    { f:'Perba 8 2019 Keselamatan Operasi Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2019 – Keselamatan Operasi Reaktor Nondaya', tag:['instalasi'] },
  ]},

  { id:'s4f', title:'Peraturan BAPETEN 2018', cat:'perka', items:[
    { f:'Perba 2 2018 Uji Kesesuaian Pesawat Sinar X Diagnostik dan Interventional.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2018 – Uji Kesesuaian Pesawat Sinar-X Radiologi Diagnostik dan Intervensional', tag:['medik'] },
    { f:'Perba 4 2018 Ketentuan Keselamatan Evaluasi Tapak IN.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2018 – Ketentuan Keselamatan Evaluasi Tapak Instalasi Nuklir', tag:['instalasi'] },
    { f:'Perba 5 2018 Pelayanan Perizinan Pemanfaatan Nuklir Secara Elektronik.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2018 – Pelayanan Perizinan Pemanfaatan Tenaga Nuklir Secara Elektronik', tag:['industri','medik','instalasi'] },
    { f:'Perba 6 2018 Persyaratan dan Tata Cara Perizinan Berusaha Terintegrasi secara Elektronik....pdf',
      t:'Perba BAPETEN No. 6 Tahun 2018 – Persyaratan Tata Cara Perizinan Berusaha Terintegrasi Secara Elektronik Sektor Ketenaganukliran', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4g', title:'Peraturan BAPETEN 2017', cat:'perka', items:[
    { f:'Perba 2 2017 Lartas Impor Ekspor.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2017 – Larangan dan Pembatasan Impor dan Ekspor Barang Konsumen, SRP, dan Bahan Nuklir', tag:['industri'] },
    { f:'Perba 7 2017 Perubahan Perba 7 2013 Nilai Batas Radioaktivitas.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2017 – Perubahan Atas Perba No. 7 Tahun 2013 Tentang Nilai Batas Radioaktivitas Lingkungan', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4h', title:'Peraturan BAPETEN 2016', cat:'perka', items:[
    { f:'Perba 5 2016 Keselamatan Radiasi Produksi Barang Konsumen.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2016 – Keselamatan Radiasi Dalam Produksi Barang Konsumen', tag:['industri'] },
    { f:'Perba 8 2016 Pengolahan Limbah Radioaktif Tingkat Rendah dan Sedang.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2016 – Pengelolaan Limbah Radioaktif Tingkat Rendah dan Tingkat Sedang', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4i', title:'Peraturan BAPETEN 2015', cat:'perka', items:[
    { f:'Perba 1 2015 Penatalaksanaan Tanggap Darurat Bapeten.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2015 – Penatalaksanaan Tanggap Darurat Badan Pengawas Tenaga Nuklir', tag:['industri','medik','instalasi'] },
    { f:'Perba 2 2015 Verifikasi dan Penilaian Keselamatan Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2015 – Verifikasi dan Penilaian Keselamatan Reaktor Nondaya',
      lamp:[{l:'Lampiran', f:'Perba 2 2015 Verifikasi dan Penilaian Keselamatan RND (Lamp).pdf'}],
      tag:['instalasi'] },
    { f:'Perka 5 2015 kegunung apian.pdf',
      t:'Perka BAPETEN No. 5 Tahun 2015 – Evaluasi Tapak Instalasi Nuklir untuk Aspek Kegunungapian', tag:['instalasi'] },
    { f:'Perba 6 2015 Keamanan Sumber Radioaktif.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2015 – Keamanan Sumber Radioaktif', tag:['industri','medik'] },
    { f:'Perka 9 2015 perawatan INNR.pdf',
      t:'Perka BAPETEN No. 9 Tahun 2015 – Perawatan Instalasi Nuklir Non Reaktor', tag:['instalasi'] },
    { f:'Perba 9 2015 Ketentuan Perawatan INNR.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2015 – Ketentuan Perawatan INNR', tag:['instalasi'] },
    { f:'Perba 11 2015 Lab Dosimetri Eksterna.pdf',
      t:'Perba BAPETEN No. 11 Tahun 2015 – Laboratorium Dosimetri Eksternal', tag:['industri','medik'] },
  ]},

  { id:'s4j', title:'Peraturan BAPETEN 2014', cat:'perka', items:[
    { f:'Perba 2 2014 Manajemen Teras Serta Penanganan BBN RND.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2014 – Manajemen Teras serta Penanganan dan Penyimpanan Bahan Bakar Nuklir Pada Reaktor Nondaya', tag:['instalasi'] },
    { f:'Perba 3 2014 Penyusunan Dokumen AMDAL Bidang Ketenaganukliran.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2014 – Penyusunan Dokumen AMDAL Bidang Ketenaganukliran', tag:['instalasi'] },
    { f:'Perba 4 2014 BKO INNR.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2014 – Batasan dan Kondisi Operasi Instalasi Nuklir Nonreaktor',
      lamp:[{l:'Lamp I', f:'Perba 4 2014 BKO INNR (Lamp I).pdf'},{l:'Lamp II', f:'Perba 4 2014 BKO (Lamp II).pdf'},{l:'Lamp III', f:'Perba 4 2014 BKO INNR (Lamp III).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 6 2014 Evaluasi Tapak IN Aspek Meteorogi dan Hidrologi.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2014 – Evaluasi Tapak Instalasi Nuklir untuk Aspek Meteorologi dan Hidrologi', tag:['instalasi'] },
    { f:'Perba 8 2014 Perubahan Perba 7 2009 Penggunaan Radiografi Industri.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2014 – Perubahan Atas Perba No. 7 Tahun 2009 Tentang Keselamatan Radiasi Dalam Penggunaan Peralatan Radiografi Industri', tag:['industri'] },
    { f:'Perba 10 2014 Penatausahaan PNBP.pdf',
      t:'Perba BAPETEN No. 10 Tahun 2014 – Penatausahaan PNBP Pada BAPETEN', tag:['industri','medik','instalasi'] },
    { f:'Perba 15 2014 Keselamatan Radiasi dalam Produksi Pesawat Sinar X.pdf',
      t:'Perba BAPETEN No. 15 Tahun 2014 – Keselamatan Radiasi Dalam Produksi Pesawat Sinar-X Radiologi Diagnostik dan Intervensional', tag:['medik','industri'] },
    { f:'Perba 16 2014 SIB Petugas Tertentu di Instalasi SRP (Lamp I).pdf',
      t:'Perba BAPETEN No. 16 Tahun 2014 – Surat Izin Bekerja Petugas Tertentu Di Instalasi Yang Memanfaatkan SRP (Lampiran I)', tag:['industri','medik'] },
  ]},

  { id:'s4k', title:'Peraturan BAPETEN 2013', cat:'perka', items:[
    { f:'Perba 1 2013 Perubahan Perba 3 2012 Penatausahaan PNBP.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2013 – Perubahan Atas Perba No. 3 Tahun 2012 Tentang Penatausahaan PNBP', tag:['industri','medik','instalasi'] },
    { f:'Perba 3 2013 Keselamatan Radiasi Radioterapi.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2013 – Keselamatan Radiasi Dalam Penggunaan Radioterapi', tag:['medik'] },
    { f:'Perba 4 2013 Proteksi dan Keselamatan Radiasi .pdf',
      t:'Perba BAPETEN No. 4 Tahun 2013 – Proteksi dan Keselamatan Radiasi Dalam Pemanfaatan Tenaga Nuklir',
      lamp:[{l:'Lamp I', f:'Perba 4 2013 Proteksi dan Keselamatan Radiasi (Lamp I).pdf'},{l:'Lamp II', f:'Perba 4 2013 Proteksi dan Keselamatan Radiasi dalam Pemanfaatan Nuklir (Lamp II).pdf'}],
      tag:['industri','medik','instalasi'] },
    { f:'Perba 6 2013 Izin Bekerja Petugas IBN.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2013 – Izin Bekerja Petugas Instalasi dan Bahan Nuklir',
      lamp:[{l:'Lamp I', f:'Perba 6 2013 Izin Bekerja Petugas IN (Lampiran I).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 7 2013 Nilai Batas Radioaktivitas Lingkungan.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2013 – Nilai Batas Radioaktivitas Lingkungan',
      lamp:[{l:'Lamp I', f:'Perba 7 2013 Nilai Batas Radioaktivitas Lingkungan (Lamp I).pdf'},{l:'Lamp III', f:'Perba 7 2013 Nilai Batas Radioaktivitas Lingkungan (Lamp III).pdf'}],
      tag:['industri','medik','instalasi'] },
    { f:'Perba 8 2013 Evaluasi Tapak IN Aspek Kegempaan.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2013 – Evaluasi Tapak Instalasi Nuklir untuk Aspek Kegempaan', tag:['instalasi'] },
    { f:'Perba 9 2013 BKKO RND.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2013 – Batasan dan Kondisi Operasi Reaktor Nondaya',
      lamp:[{l:'Lamp II', f:'Perba 9 2013 BKO RND (Lamp II).pdf'},{l:'Lamp III', f:'Perba 9 2013 BKO RND (Lamp III).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 9 2013 BKO Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2013 – BKO Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 16 2013 Keselamatan Radiasi TENORM.pdf',
      t:'Perba BAPETEN No. 16 Tahun 2013 – Keselamatan Radiasi Dalam Penyimpanan TENORM', tag:['industri'] },
    { f:'Perba 17 2013 Keselamatan Radiasi Impor, Ekspor Pengalihan Barang Konsumen.pdf',
      t:'Perba BAPETEN No. 17 Tahun 2013 – Keselamatan Radiasi Dalam Kegiatan Impor, Ekspor, dan Pengalihan Barang Konsumen', tag:['industri'] },
    { f:'Perba 17 2013 Keselamatan Radiasi Impor, Ekspor dan Pengalihan Barang Konsumen.pdf',
      t:'Perba BAPETEN No. 17 Tahun 2013 – Keselamatan Radiasi Impor, Ekspor dan Pengalihan Barang Konsumen', tag:['industri'] },
    { f:'Perba 17 2013 Keselamatan Radiasi Impor, Ekspor, Pengalihan Barang Konsumen.pdf',
      t:'Perba BAPETEN No. 17 Tahun 2013 – Keselamatan Radiasi Impor, Ekspor, Pengalihan Barang Konsumen', tag:['industri'] },
  ]},

  { id:'s4l', title:'Peraturan BAPETEN 2012', cat:'perka', items:[
    { f:'Perba 1 2012 Ketentuan Desain Sistem Proteksi Kebakaran dan Ledakan Internal RD.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2012 – Ketentuan Desain Sistem Proteksi Terhadap Kebakaran dan Ledakan Internal Pada Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 2 2012 Desain Proteksi Bahaya Internal Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2012 – Desain Proteksi Terhadap Bahaya Internal Selain Kebakaran dan Ledakan Pada Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 3 2012 Penatausahaan PNBP.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2012 – Penatausahaan PNBP Pada BAPETEN', tag:['industri','medik','instalasi'] },
    { f:'Perba 5 2012 Keselamatan dalam Utilisasi dan Modifikasi RND.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2012 – Keselamatan Dalam Utilisasi dan Modifikasi Reaktor Nondaya', tag:['instalasi'] },
    { f:'Perba 6 2012 Desain Sistem Keselamatan berbasis komputer Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2012 – Desain Sistem Yang Penting untuk Keselamatan Berbasis Komputer Pada Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 7 2012 Manajemen Penuaan INNR.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2012 – Manajemen Penuaan Instalasi Nuklir Nonreaktor',
      lamp:[{l:'Nilai Batas Radioaktivitas Lamp II', f:'Perba 7 2012 Nilai Batas Radioaktivitas Lingkungan (Lamp II).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 8 2012 Penyusunan LAK RND.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2012 – Penyusunan Laporan Analisis Keselamatan Reaktor Non Daya',
      lamp:[{l:'Lamp I', f:'Perba 8 2012 Penyusunan LAK Reaktor Non Daya (Lamp I).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 12 2012 Pemberlakukan Sistem Elektronik INSW.pdf',
      t:'Perba BAPETEN No. 12 Tahun 2012 – Pemberlakuan Sistem Elektronik Dalam Kerangka INSW di Lingkungan BAPETEN', tag:['industri','medik'] },
    { f:'Perba 16 2012 Tingkat Klierens.pdf',
      t:'Perba BAPETEN No. 16 Tahun 2012 – Tingkat Klierens',
      lamp:[{l:'Lamp I', f:'Perba 16 2012 Tingkat Klierens (Lamp I).pdf'},{l:'Lamp II', f:'Perba 16 2012 Tingkat Klierens (Lamp II).pdf'}],
      tag:['industri','medik','instalasi'] },
    { f:'Perba 17 2012 Keselamatan Radiasi Kedokteran Nuklir.pdf',
      t:'Perba BAPETEN No. 17 Tahun 2012 – Keselamatan Radiasi Dalam Kedokteran Nuklir',
      lamp:[{l:'Lamp I', f:'Perba 17 2012 Keselamatan Radiasi Kedokteran Nuklir (Lamp I).pdf'}],
      tag:['medik'] },
  ]},

  { id:'s4m', title:'Peraturan BAPETEN 2011', cat:'perka', items:[
    { f:'Perba 1 2011 KEtentuan Keselamatan Desain RND.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2011 – Ketentuan Keselamatan Desain Reaktor Nondaya',
      lamp:[{l:'Lamp I', f:'Perba 1 2011 Ketentuan Keselamatan RND (Lamp I).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 2 2011 Ketentuan Keselamatan Operasi RND.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2011 – Ketentuan Keselamatan Operasi Reaktor Nondaya', tag:['instalasi'] },
    { f:'Perba 3 2011 Ketentuan Keselamatan Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2011 – Ketentuan Keselamatan Desain Reaktor Daya',
      lamp:[{l:'Lamp I', f:'Perba 3 2011 Ketentuan Keselamatan Desain REaktor Daya (Lamp I).pdf'},{l:'Lamp III', f:'Perba 3 2011 Ketentuan Keselamatan Desain RD (Lamp III).pdf'}],
      tag:['instalasi'] },
    { f:'Perba 4 2011 Sistem Seifgard.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2011 – Sistem Seifgard', tag:['instalasi'] },
    { f:'Perba 5 2011 Ketentuan Perawatan RND.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2011 – Ketentuan Perawatan Reaktor Nondaya', tag:['instalasi'] },
    { f:'Perba 6 2011 Dekomisining INNR.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2011 – Dekomisioning Instalasi Nuklir Non Reaktor', tag:['instalasi'] },
    { f:'Perba 7 2011 Desain SIstem Catu Daya Darurat RD.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2011 – Desain Sistem Catu Daya Darurat untuk Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 8 2011 Keselamatan Radiasi Pesawat RDI.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2011 – Keselamatan Radiasi Dalam Penggunaan Pesawat Sinar-X Radiologi Diagnostik dan Intervensional', tag:['medik'] },
    { f:'Perba 9 2011 Uji Kesesuaian Pesawat Sinar X RDI.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2011 – Uji Kesesuaian Pesawat Sinar-X Radiologi Diagnostik dan Intervensional', tag:['medik'] },
    { f:'Perba 10 2011 Sistem Manajemen Bapeten.pdf',
      t:'Perba BAPETEN No. 10 Tahun 2011 – Sistem Manajemen Badan Pengawas Tenaga Nuklir', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4n', title:'Peraturan BAPETEN 2010', cat:'perka', items:[
    { f:'Perba 1 2010 Kesiapsiagaan dan Penanggulangan Kedaruratan Nuklir.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2010 – Kesiapsiagaan dan Penanggulangan Kedaruratan Nuklir', tag:['industri','medik','instalasi'] },

    { f:'Perba 3 2010 Desain Sistem Penanganan BBN Reaktor Daya.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2010 – Desain Sistem Penanganan dan Penyimpanan Bahan Bakar Nuklir untuk Reaktor Daya', tag:['instalasi'] },
    { f:'Perba 4 2010 Sistem Manajemen Fasilitas dan Kegiatan Pemanfaatan .pdf',
      t:'Perba BAPETEN No. 4 Tahun 2010 – Sistem Manajemen Fasilitas dan Kegiatan Pemanfaatan Tenaga Nuklir', tag:['industri','medik','instalasi'] },
    { f:'Perba 6 2010 Pemantauan Kesehatan Pekerja Radiasi.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2010 – Pemantauan Kesehatan untuk Pekerja Radiasi', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4o', title:'Peraturan BAPETEN 2009', cat:'perka', items:[
    { f:'Perba 1 2009 Ketentuan Sistem Proteksi Fisik IBN.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2009 – Ketentuan Sistem Proteksi Fisik Instalasi dan Bahan Nuklir', tag:['instalasi'] },
    { f:'Perba 2 2009 Penyusunan DID.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2009 – Penyusunan Daftar Informasi Desain', tag:['instalasi'] },
    { f:'Perba 4 2009 Dekomisionin Reaktor Nuklir.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2009 – Dekomisioning Reaktor Nuklir', tag:['instalasi'] },
    { f:'Perba 5 2009 Keselamatan Radiasi Well Logging.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2009 – Keselamatan Radiasi Dalam Penggunaan ZR untuk Well Logging', tag:['industri'] },
    { f:'Perba 6 2009 Keselamatan Radiasi Gauging.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2009 – Keselamatan Radiasi Dalam Penggunaan ZR dan Pesawat Sinar-X untuk Peralatan Gauging', tag:['industri'] },
    { f:'Perba 7 2009 Keselamatan Radiasi Radiografi Industri.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2009 – Keselamatan Radiasi Dalam Penggunaan Peralatan Radiografi Industri', tag:['industri'] },
    { f:'Perba 9 2009 Intervensi Paparan Tenorm.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2009 – Intervensi Terhadap Paparan Yang Berasal Dari TENORM', tag:['industri'] },
  ]},

  { id:'s4p', title:'Peraturan BAPETEN 2008', cat:'perka', items:[
    { f:'Perba 1 2008 Evaluasi Tapak Reaktor Daya (Aspek Kegempaan).pdf',
      t:'Perba BAPETEN No. 1 Tahun 2008 – Evaluasi Tapak Reaktor Daya untuk Aspek Kegempaan', tag:['instalasi'] },
    { f:'Perba 2 2008 Evaluasi Tapak Reaktor Daya Aspek Kegunungapian.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2008 – Evaluasi Tapak Reaktor Daya untuk Aspek Kegunungapian', tag:['instalasi'] },
    { f:'Perba 3 2008 Evaluasi Tapak Reaktor Daya Aspek Dispersi ZR dan Distribusi.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2008 – Evaluasi Tapak Reaktor Daya untuk Aspek Penentuan Dispersi ZR Di Udara dan Air', tag:['instalasi'] },
    { f:'Perba 4 2008 Evaluasi Tapak Reaktor Daya Aspek Geoteknik.pdf',
      t:'Perba BAPETEN No. 4 Tahun 2008 – Evaluasi Tapak Reaktor Daya untuk Aspek Geoteknik dan Pondasi', tag:['instalasi'] },
    { f:'Perba 5 2008 Pedoman Evaluasi Tapak Reaktor Daya Aspek Meteorologi.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2008 – Pedoman Evaluasi Tapak Reaktor Daya untuk Aspek Meteorologi', tag:['instalasi'] },
    { f:'Perba 6 2008 Evaluasi Tapak Reaktor Daya Aspek Kejadian Eksternal.pdf',
      t:'Perba BAPETEN No. 6 Tahun 2008 – Evaluasi Tapak Reaktor Daya untuk Aspek Kejadian Eksternal Akibat Ulah Manusia', tag:['instalasi'] },
    { f:'Perba 8 2008 Ketentuan Keselamatan Manajemen Penuaan RN.pdf',
      t:'Perba BAPETEN No. 8 Tahun 2008 – Ketentuan Keselamatan Manajemen Penuaan Reaktor Nondaya', tag:['instalasi'] },
    { f:'Perba 9 2008 Penyusunan dan Format Deklarasi Pelaksanaan Protokol Tambahan.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2008 – Penyusunan dan Format Deklarasi Dalam Pelaksanaan Protokol Tambahan', tag:['instalasi'] },
    { f:'Perba 10 2008 Izin Bekerja Petugas IBN.pdf',
      t:'Perba BAPETEN No. 10 Tahun 2008 – Izin Bekerja Petugas Instalasi dan Bahan Nuklir', tag:['instalasi'] },
    { f:'Perba 14 2008 PEncabutan Perba 18 2000 Sertifikasi dan Akreditasi Lembaga Sertifikasi.pdf',
      t:'Perba BAPETEN No. 14 Tahun 2008 – Pencabutan Perba No. 18/2000 Tentang Sertifikasi dan Akreditasi Lembaga Sertifikasi', tag:['industri','medik','instalasi'] },
    { f:'Perba 15 2008 Persyaratan memperoleh SIB bagi petugas Tertentu.pdf',
      t:'Perba BAPETEN No. 15 Tahun 2008 – Persyaratan untuk Memperoleh Surat Izin Bekerja Petugas Tertentu', tag:['industri','medik'] },
  ]},

  { id:'s4q', title:'Peraturan BAPETEN 2007', cat:'perka', items:[
    { f:'Perba 5 2007 Ketentuan Keselamatan Evaluasi Tapak RN.pdf',
      t:'Perba BAPETEN No. 5 Tahun 2007 – Ketentuan Keselamatan Evaluasi Tapak Reaktor Nuklir', tag:['instalasi'] },
    { f:'Perba 7 2007 Keamanan Sumber Radioaktif.pdf',
      t:'Perba BAPETEN No. 7 Tahun 2007 – Keamanan Sumber Radioaktif', tag:['industri','medik'] },
    { f:'Perba 11 2007 Ketentuan Keselamatan INNR.pdf',
      t:'Perba BAPETEN No. 11 Tahun 2007 – Ketentuan Keselamatan Instalasi Nuklir Non Reaktor', tag:['instalasi'] },
    { f:'Perba 14 2007 Satuan Tanggap Darurat.pdf',
      t:'Perba BAPETEN No. 14 Tahun 2007 – Satuan Tanggap Darurat', tag:['industri','medik','instalasi'] },
  ]},

  { id:'s4r', title:'Peraturan BAPETEN 2006', cat:'perka', items:[
    { f:'Perba 1 2006 Laboratorium Dosimetri, KAlibrasi AUR, dan Keluaran Sumber Terapi.pdf',
      t:'Perba BAPETEN No. 1 Tahun 2006 – Laboratorium Dosimetri, Kalibrasi Alat Ukur Radiasi dan Keluaran Sumber Radiasi Terapi', tag:['medik','industri'] },
    { f:'Perba 3 2006 Perizinan INNR.pdf',
      t:'Perba BAPETEN No. 3 Tahun 2006 – Perizinan Instalasi Nuklir Non Reaktor', tag:['instalasi'] },
    { f:'Perba 9 2006 Pelaksanaan Protokol Tambahan SPPBN.pdf',
      t:'Perba BAPETEN No. 9 Tahun 2006 – Pelaksanaan Protokol Tambahan Pada Sistem Pertanggungjawaban dan Pengendalian Bahan Nuklir', tag:['instalasi'] },
    { f:'Perba 10 2006 Pedoman Penyusunan LAK INNR.pdf',
      t:'Perba BAPETEN No. 10 Tahun 2006 – Pedoman Penyusunan Laporan Analisis Keselamatan Instalasi Nuklir Nonreaktor', tag:['instalasi'] },
  ]},

  { id:'s4s', title:'Peraturan BAPETEN 2005', cat:'perka', items:[
    { f:'Perba 2 2005 Sistem Pertanggungjawaban dan Pengendalian Bahan Nuklir.pdf',
      t:'Perba BAPETEN No. 2 Tahun 2005 – Sistem Pertanggungjawaban dan Pengendalian Bahan Nuklir', tag:['instalasi'] },
  ]},

  { id:'s4t', title:'Peraturan BAPETEN 1999', cat:'perka', items:[
    { f:'Perba 06 1999 Pembangunaan dan Pengoperasian RN.pdf',
      t:'Perba BAPETEN No. 6 Tahun 1999 – Pembangunan dan Pengoperasian Reaktor Nuklir', tag:['instalasi'] },
  ]},

  // ══════════════════════════════════════════════════════════
  // KEPUTUSAN KEPALA BAPETEN
  // ══════════════════════════════════════════════════════════
  { id:'s5a', title:'Keputusan Kepala BAPETEN 2003', cat:'kepka', items:[
    { f:'Kepka 01P 2003 Pedoman Dosis Pasien Radiodiagnostik.pdf',
      t:'Kepka BAPETEN No. 01-P Tahun 2003 – Pedoman Dosis Pasien Radiodiagnostik', tag:['medik'] },
    { f:'Kepka 02P 2003 Sistem Pelayanan Pemantauan Dosis Eksterna.pdf',
      t:'Kepka BAPETEN No. 02-P Tahun 2003 – Sistem Pelayanan Pemantauan Dosis Eksterna Perorangan', tag:['industri','medik'] },
    { f:'Kepka 03-P 2003 Persyaratan Laboratorium Uji Bungkusan.pdf',
      t:'Kepka BAPETEN No. 03-P Tahun 2003 – Persyaratan Laboratorium Uji Bungkusan Zat Radioaktif Tipe A dan Tipe B', tag:['industri'] },
    { f:'Kepka 04P 2003 Pedoman Pelatihan Operator dan Supervisor RN.pdf',
      t:'Kepka BAPETEN No. 04-P Tahun 2003 – Pedoman Pelatihan Operator dan Supervisor Reaktor Nuklir', tag:['instalasi'] },
    { f:'Kepka 05P 2003 Pedoman Rancana Penanggulangan Keadaan Darurat.pdf',
      t:'Kepka BAPETEN No. 05-P Tahun 2003 – Pedoman Rencana Penanggulangan Keadaan Darurat', tag:['industri','medik','instalasi'] },
    { f:'Kepka 07P 2002 Pedoman Dekomisioning Medis, Industri dan INNR.pdf',
      t:'Kepka BAPETEN No. 07-P Tahun 2002 – Pedoman Dekomisioning Medis, Industri dan INNR', tag:['medik','industri','instalasi'] },
  ]},

  { id:'s5b', title:'Keputusan Kepala BAPETEN 2002', cat:'kepka', items:[
    { f:'Kepka 21 2002 Program Jaminan Kualitas Instalasi Radioterapi.pdf',
      t:'Kepka BAPETEN No. 21 Tahun 2002 – Program Jaminan Kualitas Instalasi Radioterapi', tag:['medik'] },
  ]},

  { id:'s5c', title:'Keputusan Kepala BAPETEN 2000', cat:'kepka', items:[
    { f:'Kepka 05P 2000 Pedoman Persyaratan Pengangkutan ZR.pdf',
      t:'Kepka BAPETEN No. 05-P Tahun 2000 – Pedoman Persyaratan untuk Keselamatan Pengangkutan Zat Radioaktif', tag:['industri','medik'] },
    { f:'Kepka 06P Pedoman Pembuatan LAK Reaktor Penelitian.pdf',
      t:'Kepka BAPETEN No. 06-P – Pedoman Pembuatan Laporan Analisis Keselamatan Reaktor Penelitian', tag:['instalasi'] },
  ]},

  { id:'s5d', title:'Keputusan Kepala BAPETEN 1999', cat:'kepka', items:[
    { f:'Kepka 01 1999 Ketentuan Keselamatan Kerja Radiasi.pdf',
      t:'Kepka BAPETEN No. 01 Tahun 1999 – Ketentuan Keselamatan Kerja Terhadap Radiasi', tag:['industri','medik','instalasi'] },
    { f:'Kepka 01P 1999 Pedoman Penentuan Tapak Reaktor Nuklir.pdf',
      t:'Kepka BAPETEN No. 01-P Tahun 1999 – Pedoman Penentuan Tapak Reaktor Nuklir', tag:['instalasi'] },
    { f:'Kepka 02 1999 Baku Tingkat Radioaktivitas Lingkungan.pdf',
      t:'Kepka BAPETEN No. 02 Tahun 1999 – Baku Tingkat Radioaktivitas Di Lingkungan', tag:['industri','medik','instalasi'] },
    { f:'Kepka 03 1999 Ketentuan Keselamatan Pengelolaan Limbah Radioaktif.pdf',
      t:'Kepka BAPETEN No. 03 Tahun 1999 – Ketentuan Keselamatan untuk Pengelolaan Limbah Radioaktif', tag:['industri','medik','instalasi'] },
    { f:'Kepka 4 1999 Ketentuan Keselamatan Pengangkutan ZR.pdf',
      t:'Kepka BAPETEN No. 04 Tahun 1999 – Ketentuan Keselamatan untuk Pengangkutan Zat Radioaktif', tag:['industri','medik'] },
    { f:'Kepka 04P 1999 Pedoman Teknis Penyusunan AMDAL.pdf',
      t:'Kepka BAPETEN No. 04-P Tahun 1999 – Pedoman Teknis Penyusunan AMDAL Rencana Pembangunan dan Pengoperasian Instalasi Nuklir', tag:['instalasi'] },
    { f:'Kepka 05 1999 Ketentuan Keselamatan Disain Reaktor Penelitian.pdf',
      t:'Kepka BAPETEN No. 05 Tahun 1999 – Ketentuan Keselamatan Desain Reaktor Penelitian', tag:['instalasi'] },
    { f:'Kepka 07 1999 Jaminan Mutu IN.pdf',
      t:'Kepka BAPETEN No. 07 Tahun 1999 – Jaminan Kualitas Instalasi Nuklir', tag:['instalasi'] },
    { f:'Kepka 10 1999 Ketentuan Keselamatan Operasi Reaktor Penelitian.pdf',
      t:'Kepka BAPETEN No. 10 Tahun 1999 – Ketentuan Keselamatan Operasi Reaktor Penelitian', tag:['instalasi'] },
    { f:'Kepka 11 1999 Izin Konstruksi dan Operasi Iradiator.pdf',
      t:'Kepka BAPETEN No. 11 Tahun 1999 – Izin Konstruksi dan Operasi Iradiator', tag:['industri'] },
    { f:'Kepka 12 1999 Ketentuan Keselamatan Penambangan Bahan Galian Radioaktif.pdf',
      t:'Kepka BAPETEN No. 12 Tahun 1999 – Ketentuan Keselamatan Kerja Penambangan dan Pengolahan Bahan Galian Radioaktif', tag:['industri'] },
    { f:'Kepka 14 1999 Ketentuan Keselamatan Pabrik Kaos Lampu.pdf',
      t:'Kepka BAPETEN No. 14 Tahun 1999 – Ketentuan Keselamatan Pabrik Kaos Lampu', tag:['industri'] },
  ]},

];
